# --- Server Port ---
server.port=8761

# --- Spring Application Name ---
# Este nombre es importante para que el Docker Compose lo encuentre
spring.application.name=eureka-server

# --- Eureka Server Configuration ---
# Le decimos al servidor que NO debe intentar registrarse consigo mismo
eureka.client.register-with-eureka=false

# Le decimos que NO debe intentar buscar a otros servidores
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false
# Le indicamos el nombre que usará el host dentro de la red Docker
eureka.instance.hostname=eureka-server

# Configuramos la zona de servicio (aunque no la use, es buena práctica)
eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/
