spring.application.name=servicioprofesionales

# Configuraci�n de la base de datos (Postgres en Docker)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecto para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Estrategia de generaci�n de tablas
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en logs (�til para debug)
spring.jpa.show-sql=true
